# -*- coding: utf-8 -*-
"""Trend_monitoring (without seasonal).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gzk1zW1MPVj4hwjRhgKpnmQbejKaqjB-
"""

import ee
import geemap
!pip install xee
import xee
import xarray as xr
import matplotlib.pyplot as plt

ee.Authenticate()
ee.Initialize(
    project = 'ee-lavibas23',
    opt_url = 'https://earthengine-highvolume.googleapis.com'
)

# Define AOI: Polonnaruwa paddy area (Minneriya–Elahera)
coords = [
    [80.888, 8.030],  # SW
    [81.050, 8.030],  # SE
    [81.050, 8.200],  # NE
    [80.888, 8.200],  # NW
    [80.888, 8.030]   # Close polygon
]
roi = ee.Geometry.Polygon([coords])
roi

collection = (
    ee.ImageCollection("IDAHO_EPSCOR/TERRACLIMATE")
    .filterDate('1980','2025')
    .select('def')
    .map(lambda img: img.multiply(0.1).copyProperties(img, img.propertyNames()))
)

collection

ds = xr.open_dataset(
    collection,
    engine = 'ee',
    crs = 'EPSG:4326',
    geometry = roi,
    scale = 0.001
)

ds

ds_mean = ds.mean(dim = ['lon', 'lat'])

df = ds_mean.to_dataframe()

df.plot()

from statsmodels.tsa.seasonal import seasonal_decompose

model = seasonal_decompose(
    df['def'],
    model = 'additive',
    period = 12
)

model.plot()
plt.plot()

df_trend = model.trend

df_trend.plot()

!pip install pymannkendall
import pymannkendall as mk
!pip install pyhomogeneity
import pyhomogeneity as hg

mk_test = mk.original_test(df_trend)
hg_test = hg.pettitt_test(df_trend)
print(f'mk_test: {mk_test}')
print(f'hg_test: {hg_test}')